language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "veronyannick"
# command to run tests
script:
  - pytest -v --cov .
  - sonar-scanner
  - coveralls
